export const ALL_GENRE_SUCCESS = "ALL_GENRE_SUCCESS";
export const ALL_GENRE_FAIL = "ALL_GENRE_FAIL";
export const ALL_GENRE_REQUEST = "ALL_GENRE_REQUEST";

export const ACTIVE_GENRE = "ACTIVE_GENRE"

export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL"
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST"
export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS"